config/routes.rb
Rails.application.routes.draw do
  
  #root 'home#index'
  #root to: "home#index"
  #root to: "shogi#index"
  
  #root to: "shogi#game_lobby_auto_matching"
  root to: "matching#game_lobby_matching_board"
  
  post 'matching/start', to: 'matching#start', as: :start_matching
  get 'matching/status', to: 'matching#status', as: :matching_status # ポーリング用
  post 'matching/cancel', to: 'matching#cancel', as: :cancel_matching
  post 'matching/all_delete', to: 'matching#all_delete', as: :all_delete_matching_data #開発用のマッチングデータ削除用

  get '/shogi/:id', to: 'shogi#index'
  delete '/shogi/:id/destroy', to: 'shogi#destroy'#試合終了後にデータ削除

  #get 'shogi/index'
  #get '/'  => 'home#index'
  mount ActionCable.server => '/cable'

  resources :home, only: [:index, :create] do
    member do
      post 'join'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_session_id

  def index
    @battles = Battle.where(status: 'waiting')
    #@battles = 1
  end

  def create
    @battle = Battle.new(creator_id: session[:user_id], status: 'waiting' ,mode: 'typing')
    if @battle.save
      redirect_to root_path, notice: '対戦予約が作成されました'
    else
      render :index
    end
  end

  def join
    @battle = Battle.find(params[:id])
    if @battle.update(opponent_id: session[:user_id], status: 'matched')
      redirect_to root_path, notice: '対戦に参加しました'
      #ifでリダイレクト先
    else
      redirect_to root_path, alert: '対戦への参加に失敗しました'
    end
  end

  private

  def set_session_id
    unless session[:user_id]
      session[:user_id] = SecureRandom.uuid
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag "home" %>
<%= javascript_pack_tag 'home/index' %>




<div class="flex flex-col justify-between h-screen bg-gray-800 p-2 mx-auto max-w-full">
  <header class="flex items-center justify-center text-gray-200 text-2xl my-5">
    <div class="text-4xl ml-3 mr-3">Propugnare</div>
    <a href="https://x.com/share?ref_src=twsrc%5Etfw" className="twitter-share-button fixed left-4 top-4 md:right-14 md:top-6 text-xl text-gray" data-show-count="false" data-text="Propugnare - プログラミングバトルアプリ" data-url="https://propugnare.online" data-size="summary" >ポスト</a><script async src="https://platform.x.com/widgets.js"></script>
  </header>



<a class="fixed left-4 top-4 md:right-14 md:top-6 text-xl text-white" href="https://github.com/H-Hp/propugnare">
    <button class="fixed right-12 top-4 md:right-12 md:top-6 text-xl text-white github-button">
        <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
            <path d="M511.6 76.3C264.3 76.2 64 276.4 64 523.5 64 718.9 189.3 885 363.8 946c23.5 5.9 19.9-10.8 19.9-22.2v-77.5c-135.7 15.9-141.2-73.9-150.3-88.9C215 726 171.5 718 184.5 703c30.9-15.9 62.4 4 98.9 57.9 26.4 39.1 77.9 32.5 104 26 5.7-23.5 17.9-44.5 34.7-60.8-140.6-25.2-199.2-111-199.2-213 0-49.5 16.3-95 48.3-131.7-20.4-60.5 1.9-112.3 4.9-120 58.1-5.2 118.5 41.6 123.2 45.3 33-8.9 70.7-13.6 112.9-13.6 42.4 0 80.2 4.9 113.5 13.9 11.3-8.6 67.3-48.8 121.3-43.9 2.9 7.7 24.7 58.3 5.5 118 32.4 36.8 48.9 82.7 48.9 132.3 0 102.2-59 188.1-200 212.9a127.5 127.5 0 0 1 38.1 91v112.5c.8 9 0 17.9 15 17.9 177.1-59.7 304.6-227 304.6-424.1 0-247.2-200.4-447.3-447.5-447.3z">
            </path>
        </svg>
    </button>
</a>
<button class="fixed right-4 top-4 md:right-6 md:top-6 text-xl text-white animate-pulse-once info-button">
  <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 1024 1024" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
    <path d="M512 64C264.6 64 64 264.6 64 512s200.6 448 448 448 448-200.6 448-448S759.4 64 512 64zm0 820c-205.4 0-372-166.6-372-372s166.6-372 372-372 372 166.6 372 372-166.6 372-372 372z"></path>
    <path d="M464 336a48 48 0 1 0 96 0 48 48 0 1 0-96 0zm72 112h-48c-4.4 0-8 3.6-8 8v272c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V456c0-4.4-3.6-8-8-8z">
    </path>
  </svg>
</button>
<div class="flex w-full flex-grow overflow-hidden relative">
  <div id="chat" class="flex flex-col w-full lg:w-3/5 mr-4 mx-5 lg:mx-0">
    <div id="json-zu" class="border-2 border-gray-600 p-6 rounded-lg overflow-y-scroll flex-grow flex flex-col justify-end bg-gray-700">
      <div>



        <table class="hooks__list">
            <thead>
                <tr>
                    <th></th>
                    <th>プレイヤー</th>
                    <th class="sortable sort"><i class="is"></i>レーティング</th>
                    <th class="sortable"><i class="is"></i>時間</th>
                    <th>モード</th>
                </tr>
            </thead>
            <tbody class="" id="reserve_tbody">
              <% @battles.each do |battle| %>
                <tr class="go-buttle-btn" onclick="go_buttle()">
                  <td></td>
                  <td>名無し</td>
                  <td></td>
                  <td>5分</td>
                  <!--td><%= battle.creator_id %></td>-->
                  <td><%= battle.mode %></td>
                </tr>
                <td><%= button_to '参加', join_home_path(battle), method: :post %></td>

              <% end %>
            </tbody>
            
        </table>



      </div>
    </div>

    
  </div>
  <div class="absolute transform translate-x-full transition-transform duration-500 ease-in-out right-0 w-2/3 h-full bg-gray-700 overflow-y-auto lg:static lg:translate-x-0 lg:w-2/5 lg:mx-2 rounded-lg">
    <div class="flex flex-col border-2 overflow-y-auto rounded-lg border-gray-500 w-full ">
      <div class="flex flex-col items-start sticky top-0 w-full">
        <div class="flex flex-col items-start lg:flex-row w-full lg:flex-wrap p-2">
        </div>   
          <div class="flex-grow w-full px-4">
            <button id="open-buttle-menu-btn" class="inline-flex items-center gap-2 justify-center rounded-md py-2 px-3 text-sm outline-offset-2 transition active:transition-none bg-zinc-600 font-semibold text-zinc-100 hover:bg-zinc-400 active:bg-zinc-800 active:text-zinc-100/70 w-full my-2 uppercase active:scale-[98%] transition-transform duration-100" style="background-color:#4f6574;color:white">
                対戦する
            </button>
          </div>
          <div class="flex p-2"></div>
      </div>
      <div class="flex flex-wrap w-full"></div>

    </div>
  </div>
  <button type="button" class="absolute left-20 transform -translate-x-12 bg-gray-800 text-white rounded-l py-2 px-4 lg:hidden">☰</button>
  </div>
</div>

<!--<button id="openModal">モーダルを開く</button>-->
<div id="myModal" class="modal">
    <div class="modal-content">
        <h2>対戦する</h2>
      <span class="close">&times;</span>
      <div class="label_select">
        <label for="sf_timeMode">ルール</label>
        <select id="sf_timeMode" name="timeMode">
            <option value="1" selected="selected">タイピングバトル</option>
        </select>
      </div>
      <!--<button id="reserve-btn">対戦する</button>-->
      <%= button_to '対戦予約を作成', home_index_path, method: :post %>

    </div>
  </div>






<!--
<%= button_to '対戦予約を作成', home_index_path, method: :post %>

<table>
  <thead>
    <tr>
      <th>作成者</th>
      <th>アクション</th>
    </tr>
  </thead>
  <tbody>
    <% @battles.each do |battle| %>
      <tr>
        <td>名無し</td>
        <td><%= battle.creator_id %></td>
        <td><%= battle.mode %></td>
        <td><%= button_to '参加', join_home_path(battle), method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->